### ISSUE TITLE
Custom Shortcuts

### ISSUE THREAD

**Issue by MEGA-Dawg68** [SethBurkart123/EvenBetterSEQTA#13]
Hey
They still don't work, this time they don't show up at all.
P.S BetterSEQTA+ be looking clean :)
![image_2023-10-13_082317975](https://github.com/SethBurkart123/EvenBetterSEQTA/assets/140035326/a1f80f97-bceb-4697-b72e-a3a6fe86eee9)
![image_2023-10-13_082342835](https://github.com/SethBurkart123/EvenBetterSEQTA/assets/140035326/1226861a-f253-4ffc-b05b-57e464fcadf5)

**Comment by SethBurkart123** [comment]
Hmmm. let me have a look into that

**Comment by SethBurkart123** [comment]
<img width="895" alt="image" src="https://github.com/SethBurkart123/EvenBetterSEQTA/assets/108050083/f05edb1f-5309-419a-86a6-a5f8b6c6caf5">
I'm not sure whats going on, because they are showing up for me on the production version of it...

**Comment by SethBurkart123** [comment]
@MEGA-Dawg68 I'll just get you to open up [chrome://extensions](chrome://extensions) and then follow what I showed here, if you're able to send me what that copies; I might be able to see if there is an issue with it.

<video src="https://github.com/SethBurkart123/EvenBetterSEQTA/assets/108050083/4a6a7272-efe5-422c-ad57-96199e3c18cf" />

**Comment by MEGA-Dawg68** [comment]
if I dont reload the page this is what I get

{DarkMode: false, animatedbk: true, bksliderinput: 50, customshortcuts: Array(1), defaultmenuorder: Array(0), …}

If I reload I get this
{DarkMode: false, animatedbk: true, bksliderinput: 50, customshortcuts: Array(1), defaultmenuorder: Array(0), …}
They are the exact same but no shortcut shows up

**Comment by SethBurkart123** [comment]
Hmmmmmmm. I'm not sure what's going on, if you go into inspect element console tab are there any errors from 'SEQTA.js'? Maybe they would help us?

**Comment by SethBurkart123** [comment]
@MEGA-Dawg68 Is this still a problem?

**Comment by MEGA-Dawg68** [comment]
Yes, the custom shortcut stays now but it will try to redirect you to a subdomain

**Comment by SethBurkart123** [comment]
Wonderful! I fixed it in 1ac8b5a8cb1a22a17aac031971bab04ac3919347
