### ISSUE TITLE
Update menu not working

### ISSUE THREAD

**Issue by SethBurkart123** [SethBurkart123/EvenBetterSEQTA#16]
It doesn't seem to work, as I had the extension open last update and no `What's new` menu appeared after updating.

**Comment by MEGA-Dawg68** [comment]
Yes that is the same for me, also could you add the whats new button back in the settings menu? It allows people to see features

**Comment by SethBurkart123** [comment]
Yeah I'll add it back, but I still need to make it show on update (not sure why it doesnt).

**Comment by SethBurkart123** [comment]
Should be fixed. I'll close it and leave it as long as it is now complete.
