### ISSUE TITLE
Browser (ungoogled chromium) cant find the settings file

### ISSUE THREAD

**Issue by Jaxx7594** [SethBurkart123/EvenBetterSEQTA#18]
When I click the settings button, it pops up with the generic file not found error. Would try to fix it now, but I'm in the middle of school.

**Comment by Jaxx7594** [comment]
<img width="275" alt="img" src="https://github.com/SethBurkart123/EvenBetterSEQTA/assets/101913901/f16b0c0c-d34b-4990-929a-8a1137ebef53">

**Comment by SethBurkart123** [comment]
Hmmm. That's interesting, it seems to work for other people (including myself), so if you manage to work out how to reproduce it or fix it yourself that would be greatly appreciated.

**Comment by Jaxx7594** [comment]
school just ended, on bus home rn, will be able to try fix it when I get home to my pc in an hour or so

**Comment by Jaxx7594** [comment]
Do you know if theres any problems with portability? I built it on a usb and installed it on a portable browser

**Comment by SethBurkart123** [comment]
I haven't done any testing, but I wouldn't think that it'd be an issue.

**Comment by SethBurkart123** [comment]
Interestingly enough, I just downloaded ungoogled chromium for testing, and it doesn't seem to work at all for me :O
<img width="1415" alt="image" src="https://github.com/SethBurkart123/EvenBetterSEQTA/assets/108050083/5af06934-df6d-462e-9a41-4d1bbe7170e8">
So there'll be a bit of fixing to do!

**Comment by Jaxx7594** [comment]
Are any connections to google services being made? Cause they'll all be blocked

**Comment by SethBurkart123** [comment]
The extension does call: chrome.storage.local.get just before this, are the chrome api's blocked?

**Comment by Jaxx7594** [comment]
I think any local api's work, just doesnt allow transmitting data to google. Has the extension been tested on normal chromium? Might just be a problem with chromium itself rather the ungoogled version

**Comment by Jaxx7594** [comment]
Srry 4 delay, my parents loaded me up with gardening chores n stuff, only just finished, will probably only try to fix it tomorrow cause im exhausted

**Comment by Jaxx7594** [comment]
@SethBurkart123 enabling cookies fixes the localstorage error, idk why though, ive never made a browser extension before so i'm not very familiar with how it all works. Its still broken though, just diff error
<img width="302" alt="image" src="https://github.com/SethBurkart123/EvenBetterSEQTA/assets/101913901/504d3861-aefc-49f0-b3bc-3dbf16931a0c">

**Comment by Jaxx7594** [comment]
<img width="687" alt="image" src="https://github.com/SethBurkart123/EvenBetterSEQTA/assets/101913901/6cabb195-ce4c-45c2-8a32-3a7f5e55e95d">

**Comment by SethBurkart123** [comment]
Ok, that's a start! We can work on this.

**Comment by MEGA-Dawg68** [comment]
I tried ungoogled chromium and It is giving me the same error as you got

**Comment by Crazypersonalph** [comment]
Hey guys, I thought it might be worth mentioning as I stumbled across this on StackOverflow some days prior, that Ungoogled Chromium's default extension policies (what extensions can and can't access/do) (`chrome://policy`) are different to normal Chrome's policies.

Could this be the problem?

**Comment by Crazypersonalph** [comment]
It might be messing with the Chrome/Chromium policies in order to remove Google spyware.

**Comment by Jaxx7594** [comment]
Thanks @Crazypersonalph for reminding me with a notification, completely forgot about this. Seems this issue was caused because of undocumented steps for building (#50). Doesn't seem like browser policies are messing with the extension, but I'll test it on an unmodified ungoogled chromium install in a sec.

**Comment by Jaxx7594** [comment]
Yeah its working just fine now, closing this issue
