### ISSUE TITLE
Themes and animated backgrounds

### ISSUE THREAD

**Issue by MEGA-Dawg68** [SethBurkart123/EvenBetterSEQTA#19]
When you select a theme it will keep the animated background on. It does not mix well and looks terrible
![Screenshot from 2023-11-12 13-33-48](https://github.com/SethBurkart123/EvenBetterSEQTA/assets/140035326/f81e2679-7629-4906-a76c-82c7370511cc)

**Comment by SethBurkart123** [comment]
Hmm, are you suggesting to auto disable it whenever someone selects a background?

**Comment by MEGA-Dawg68** [comment]
Yes, they can always enable again if they want

**Comment by MEGA-Dawg68** [comment]
What is sweep?

**Comment by SethBurkart123** [comment]
Just a little thing that might be able to automatically do it.

**Comment by MEGA-Dawg68** [comment]
Interesting, So it will search for the problems and fix it?

**Comment by SethBurkart123** [comment]
Fixed it in commit 38e21db3cad874774f5974e4e4f31abefe8b0432

**Comment by 97-42** [comment]
ok
