### ISSUE TITLE
Custom shortcuts

### ISSUE THREAD

**Issue by MEGA-Dawg68** [SethBurkart123/EvenBetterSEQTA#2]
If you refresh the page, the custom shortcuts will disappear. The icons are also not centered and are cut off. The shortcuts still stay in the shortcut settings
![image_2023-09-11_102814389](https://github.com/SethBurkart123/EvenBetterSEQTA/assets/140035326/48a1e467-6109-48db-8d68-e555429eac19)
![image_2023-09-11_102851772](https://github.com/SethBurkart123/EvenBetterSEQTA/assets/140035326/d8293006-b09d-4f9f-8e8b-c2a08c2f71b0)

**Comment by SethBurkart123** [comment]
Will have a look at that.

**Comment by SethBurkart123** [comment]
This is now fixed and has been pushed to the main branch!
