### ISSUE TITLE
Adding AI to EvenBetterSEQTA?

### ISSUE THREAD

**Issue by SethBurkart123** [SethBurkart123/EvenBetterSEQTA#20]
I propose adding AI functionality to EvenBetterSEQTA to enhance its capabilities. This will involve integrating machine learning models and natural language processing techniques to provide smarter and more efficient solutions.

**Comment by MEGA-Dawg68** [comment]
What do you mean? like a chat GPT tab or something else making EvenBetterSEQTA AI integrated? This would look epic either way!

**Comment by SethBurkart123** [comment]
For starters, I'm thinking a whole new direct message creator, that looks soo much better (the direct messages would look good for everyone, even in normal seqta). And I could have AI to help with that.

**Comment by MEGA-Dawg68** [comment]
Yes the current one is ok, but could definitely do with a make over. So did you want to have a message creator in direct messages? If so how are we going to get that to work? AI hosting would be really expensive for a free extension

**Comment by SethBurkart123** [comment]
I'm thinking of potentially using one of those free gpt systems? eg. [this](https://github.com/xtekky/gpt4free?tab=readme-ov-file#interference-openai-proxy-api-use-with-openai-python-package)

**Comment by MEGA-Dawg68** [comment]
That is smart. Will look good none the less!

**Comment by SethBurkart123** [comment]
If this feature was to be implemented we would have to find a better way to integrate it that doesn't make teachers freak out. So, I'll close it for now.

**Comment by MEGA-Dawg68** [comment]
What do you mean? I would have though teachers would love a direct message generator, they would get better messages than 'what is 2+2?'  lol

**Comment by Jaxx7594** [comment]
@SethBurkart123 You could just add a feature to turn off AI so if teachers get annoyed you can just switch it off. Don't know why they would get annoyed though

**Comment by Jaxx7594** [comment]
Also @SethBurkart123, ive found those sorta free gpt things can be rather unreliable, not sure about this specific one, but its probably unreliable too. I suggest just making the extension freemium and make the AI functionality like, $5 or something. Most people will be able to pay that if they want the feature, and it'll likely cover the cost and even generate some profit.

**Comment by Jaxx7594** [comment]
Ive got some friends who developed their own api for gpt and image generation, i might be able to get you something even cheaper than openai themselves

**Comment by Crazypersonalph** [comment]
What about a GPT window, but the user has to provide their own API key?

**Comment by Crazypersonalph** [comment]
> Also @SethBurkart123, ive found those sorta free gpt things can be rather unreliable, not sure about this specific one, but its probably unreliable too. I suggest just making the extension freemium and make the AI functionality like, $5 or something. Most people will be able to pay that if they want the feature, and it'll likely cover the cost and even generate some profit.

It's FOSS so there is not really any point.

If we were to make it closed-source, we would be breaking the license terms of some of our packages, and also we would lose the benefits of open source.

**Comment by SethBurkart123** [comment]
> > Also @SethBurkart123, ive found those sorta free gpt things can be rather unreliable, not sure about this specific one, but its probably unreliable too. I suggest just making the extension freemium and make the AI functionality like, $5 or something. Most people will be able to pay that if they want the feature, and it'll likely cover the cost and even generate some profit.
> 
> That means we would have to set up accounts, servers, databases, etc; and also worry about securing everything.
> 
> We _could_, but _should_ we

Well I read all of that stuff, there are a few options. First of all, for the main server, we could use https://www.oracle.com/au/cloud/free/
I've got a computer running on it and it's pretty great. That and maybe doing stuff with https://ai.cloudflare.com/
It uses the open source models which aren't as powerful, but much cheaper and still work great. Another option is using Claude's api.

There's a lot of ways to do it. About doing a freemium, the only thing is; would it put some people off the extension. We don't want it being like `oh they just added AI like everyone else`.

**Comment by Crazypersonalph** [comment]
I have my own Enterprise Proxmox Virtual Environment in which I host my VMs on an old laptop, we could use that for the db and server; I also have my own domain name which we could use for API requests, and I have backend experience, networking experience, and cybersecurity experience.

My main problem for adding AI to BetterSEQTA+ is why. A lot of people these days have a habit of shoving AI into places where it doesn't need to be, which just adds extra complexity to the application and doesn't really help anyone.
