### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by SashaIsTheBest** [SethBurkart123/EvenBetterSEQTA#43]
Is it gonna be coming sometime soon?

**Comment by SethBurkart123** [comment]
I'll put that up on the priorities. Will have a look, it shouldn't be too hard.

**Comment by MEGA-Dawg68** [comment]
I have been looking and it seems like it might be a entire code overhaul required.

**Comment by SethBurkart123** [comment]
I mean, with polyfills and a separate manifest.json it might work?

**Comment by SethBurkart123** [comment]
<img width="1301" alt="image" src="https://github.com/SethBurkart123/EvenBetterSEQTA/assets/108050083/03acb0cc-c8b5-4f36-8994-d1fec2611b2c">
Got it loading correctly.

**Comment by SashaIsTheBest** [comment]
Woo hoo! I would test it but I’m on a  plane right now. Thank you!

**Comment by SethBurkart123** [comment]
It's currently on the `firefox-dev` branch. I have a bit of stuff to fix like icons not working? (idk, the font is giving some issues)

**Comment by Crazypersonalph** [comment]
I'll go look through the code to see what is wrong with the firefox-dev branch

**Comment by Crazypersonalph** [comment]
As part of this, we will also need to migrate our namespace over from the `chrome` namespace to the `browser` namespace and implement firefox's polyfilling.

**Comment by Crazypersonalph** [comment]
#61

**Comment by Crazypersonalph** [comment]
Finished in 423726f
