### ISSUE TITLE
Lessons cut off if there is a music lesson

### ISSUE THREAD

**Issue by SashaIsTheBest** [SethBurkart123/EvenBetterSEQTA#44]
Title
![image](https://github.com/SethBurkart123/EvenBetterSEQTA/assets/122860170/21cb51cf-edde-4d29-8c07-ac4200df4a03)
Thats what happens with music lesson
What is should look like 
![image](https://github.com/SethBurkart123/EvenBetterSEQTA/assets/122860170/90b30f69-9803-44cb-ad94-f8b453344034)
How to replecate
Put music lesson in class like this 
![image](https://github.com/SethBurkart123/EvenBetterSEQTA/assets/122860170/c5005beb-dd18-4be0-aaaa-0dab9390d527)

**Comment by SethBurkart123** [comment]
I think I know what could be causing it, will have a look at that.

**Comment by SethBurkart123** [comment]
I have one problem. Due to not having any classes that overlap, I can't figure out a way of testing (and therefore fixing) the problem... If you have any ideas I'm all ears.

**Comment by SethBurkart123** [comment]
Fixed in d139e37. Closing the issue now, you should see an update soon.
