### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Jaxx7594** [SethBurkart123/EvenBetterSEQTA#50]
ERROR in unable to locate 'C:/Users/[redacted]/EvenBetterSEQTA/interface/dist/client' glob

ERROR in unable to locate 'C:/Users/[redacted]/EvenBetterSEQTA/interface/dist/index.html' glob

**Comment by SethBurkart123** [comment]
Hey @Jaxx7594,

Sorry that it wasn't in the documentation in the past, I recently updated it. You just have to open another terminal, `cd interface` and then install all the dependencies:
```
npm i
```
and finally
```
npm run dev
```
That needs to run at the same time as the main dev script. I separated it originally for performance, as when having them together it took a big hit on the development speed as a whole.

**Comment by Jaxx7594** [comment]
Alr, thanks! Will test it out tomorrow
