### ISSUE TITLE
Migrate codebase to Typescript

### ISSUE THREAD

**Issue by SethBurkart123** [SethBurkart123/EvenBetterSEQTA#65]
Pretty self explanatory but it would do a lot for code maintainability and quality. Less bugs, easier to implement new features or debug existing ones.

**Comment by Crazypersonalph** [comment]
Also type checking *cries in joy*

**Comment by Crazypersonalph** [comment]
PR #70

**Comment by SethBurkart123** [comment]
> PR #70

Literally cries in joy. 🥲

**Comment by Crazypersonalph** [comment]
Looks like this can be closed as completed now

**Comment by Crazypersonalph** [comment]
#72 & #73

they fix issues that have risen since implementing ts, probably because of how webpack handles them compared to vanilla JS files.
